[
    { "question": "🇦🇫", "response": "افغانستان" },
    { "question": "🇦🇨", "response": "جزر الاند" },
    { "question": "🇦🇱", "response": "البانيا" },
    { "question": "🇩🇿", "response": "الجزاير" },
    { "question": "🇦🇸", "response": "ساموا الامريكيه" },
    { "question": "🇦🇩", "response": "اندورا" },
    { "question": "🇦🇴", "response": "انغولا" },
    { "question": "🇦🇮", "response": "انغيلا" },
    { "question": "🇦🇶", "response": "القاره القطبيه الجنوبيه" },
    { "question": "🇦🇬", "response": "انتيغوا وبربودا" },
    { "question": "🇦🇷", "response": "الارجنتين" },
    { "question": "🇦🇲", "response": "ارمينيا" },
    { "question": "🇪🇺", "response": "اروبا" },
    { "question": "🇦🇺", "response": "استراليا" },
    { "question": "🇦🇹", "response": "النمسا" },
    { "question": "🇦🇿", "response": "اذربيجان" },
    { "question": "🇧🇸", "response": "جزر البهاما" },
    { "question": "🇧🇭", "response": "البحرين" },
    { "question": "🇧🇩", "response": "بنغلادش" },
    { "question": "🇧🇧", "response": "بربادوس" },
    { "question": "🇧🇾", "response": "بيلاروسيا" },
    { "question": "🇧🇪", "response": "بلجيكا" },
    { "question": "🇧🇿", "response": "بليز" },
    { "question": "🇧🇳", "response": "بنين" },
    { "question": "🇧🇲", "response": "برمودا" },
    { "question": "🇧🇹", "response": "بوتان" },
    { "question": "🇧🇴", "response": "بوليفيا" },
    { "question": "🇧🇦", "response": "البوسنه والهرك" },
    { "question": "🇧🇼", "response": "بوتسوانا" },
    { "question": "🇧🇫", "response": "جزيره بوفيه" },
    { "question": "🇧🇷", "response": "البرازيل" },
    { "question": "🇮🇴", "response": "اقليم المحيط البريطاني الهندي" },
    { "question": "🇧🇳", "response": "بروناي" },
    { "question": "🇧🇬", "response": "بلغاريا" },
    { "question": "🇧🇫", "response": "بوركينا فاسو" },
    { "question": "🇧🇮", "response": "بوروندي" },
    { "question": "🇰🇭", "response": "كمبوديا" },
    { "question": "🇨🇲", "response": "الكاميرون" },
    { "question": "🇨🇦", "response": "كاندا" },
    { "question": "🇨🇻", "response": "الرأس الاخضر" },
    { "question": "🇳🇱", "response": "هولندا الكاريبيه" },
    { "question": "🇰🇾", "response": "جزر كايمان" },
    { "question": "🇨🇫", "response": "جمهوريه افريقيا الوسطى" },
    { "question": "🇹🇩", "response": "تشاد" },
    { "question": "🇨🇱", "response": "شيلي" },
    { "question": "🇨🇳", "response": "الصين" },
    { "question": "🇨🇽", "response": "جزيره عيد الميلاد" },
    { "question": "🇨🇨", "response": "جزر كوكوس" },
    { "question": "🇨🇴", "response": "كولومبيا" },
    { "question": "🇨🇬", "response": "جمهوريه الكونغو" },
    { "question": "🇨🇩", "response": "جمهوريه الكونغو الديمقراطيه" },
    { "question": "🇨🇰", "response": "جزر كوك" },
    { "question": "🇨🇮", "response": "كوت ديفوار" },
    { "question": "🇭🇷", "response": "كرواتيا" },
    { "question": "🇨🇺", "response": "كوبا" },
    { "question": "🇨🇼", "response": "كوراساو" },
    { "question": "🇨🇾", "response": "قبرص" },
    { "question": "🇨🇿", "response": "التشيك" },
    { "question": "🇩🇰", "response": "الدنمارك" },
    { "question": "🇩🇯", "response": "جيبوتي" },
    { "question": "🇩🇲", "response": "دومينيكا" },
    { "question": "🇩🇴", "response": "جمهوريه الدومينيكان" },
    { "question": "🇪🇨", "response": "اكوادور" },
    { "question": "🇪🇬", "response": "مصر" },
    { "question": "🇸🇻", "response": "السلفادور" },
    { "question": "🇬🇧", "response": "انكلترا" },
    { "question": "🇪🇷", "response": "اريتريا" },
    { "question": "🇪🇪", "response": "استونيا" },
    { "question": "🇸🇿", "response": "ايسواتيني" },
    { "question": "🇪🇹", "response": "اثيوبيا" },
    { "question": "🇫🇰", "response": "جزر فوكلاند" },
    { "question": "🇫🇴", "response": "جزر فاروس" },
    { "question": "🇫🇯", "response": "فيجي" },
    { "question": "🇫🇮", "response": "فنلندا" },
    { "question": "🇫🇷", "response": "فرنسا" },
    { "question": "🇬🇫", "response": "غيانا الفرنسيه" },
    { "question": "🇵🇫", "response": "بولينيزيا الفرنسيه" },
    { "question": "🇹🇫", "response": "الاراضي الفرنسيه الجنوبيه والقطبيه الجنوبيه" },
    { "question": "🇬🇦", "response": "الجابون" },
    { "question": "🇬🇲", "response": "غامبيا" },
    { "question": "🇬🇪", "response": "جورجيا" },
    { "question": "🇩🇪", "response": "المانيا" },
    { "question": "🇬🇭", "response": "غانا" },
    { "question": "🇬🇮", "response": "جبل طارق" },
    { "question": "🇬🇷", "response": "اليونان" },
    { "question": "🇬🇱", "response": "الارض الخضراء" },
    { "question": "🇬🇩", "response": "غرينادا" },
    { "question": "🇬🇵", "response": "جوادلوب" },
    { "question": "🇬🇺", "response": "غوام" },
    { "question": "🇬🇹", "response": "غواتيمالا" },
    { "question": "🇬🇬", "response": "غيرنسي" },
    { "question": "🇬🇳", "response": "غينيا" },
    { "question": "🇬🇼", "response": "غينيا بيساو" },
    { "question": "🇬🇾", "response": "غيانا" }
    { "question": "🇭🇹", "response": "هايتي" },
    { "question": "🇭🇳", "response": "هندوراس" },
    { "question": "🇭🇰", "response": "هونج كونج" },
    { "question": "🇭🇺", "response": "هنغاريا" },
    { "question": "🇮🇸", "response": "ايسلندا" },
    { "question": "🇮🇳", "response": "الهند" },
    { "question": "🇮🇩", "response": "اندونيسيا" },
    { "question": "🇮🇷", "response": "ايران" },
    { "question": "🇮🇶", "response": "العراق" },
    { "question": "🇮🇪", "response": "ايرلندا" },
    { "question": "🇮🇲", "response": "جزيره ايل اوف مان" },
    { "question": "🇮🇹", "response": "ايطاليا" },
    { "question": "🇯🇲", "response": "جامايكا" },
    { "question": "🇯🇵", "response": "اليابان" },
    { "question": "🇯🇪", "response": "جيرسي" },
    { "question": "🇯🇴", "response": "الاردن" },
    { "question": "🇰🇿", "response": "كازاخستان" },
    { "question": "🇰🇪", "response": "كينيا" },
    { "question": "🇰🇮", "response": "كيريباتي" },
    { "question": "🇰🇷", "response": "كوريا الجنوبيه" },
    { "question": "🇰🇵", "response": "كوريا الشماليه" },
    { "question": "🇽🇰", "response": "كوسوفو" },
    { "question": "🇰🇼", "response": "الكويت" },
    { "question": "🇰🇬", "response": "قيرغيزستان" },
    { "question": "🇱🇦", "response": "لاوس" },
    { "question": "🇱🇻", "response": "لاتيفيا" },
    { "question": "🇱🇧", "response": "لبنان" },
    { "question": "🇱🇸", "response": "ليسوتو" },
    { "question": "🇱🇷", "response": "ليبيريا" },
    { "question": "🇱🇾", "response": "ليبيا" },
    { "question": "🇱🇮", "response": "ليختنشتاين" },
    { "question": "🇱🇹", "response": "ليتوانيا" },
    { "question": "🇱🇺", "response": "لوكسمبورغ" },
    { "question": "🇲🇴", "response": "ماكاو" },
    { "question": "🇲🇬", "response": "مدغشقر" },
    { "question": "🇲🇼", "response": "ملاوي" },
    { "question": "🇲🇾", "response": "ماليزيا" },
    { "question": "🇲🇻", "response": "جزر المالديف" },
    { "question": "🇲🇱", "response": "مالي" },
    { "question": "🇲🇹", "response": "مالطا" },
    { "question": "🇲🇭", "response": "جزر مارشال" },
    { "question": "🇲🇶", "response": "مارتينيك" },
    { "question": "🇲🇷", "response": "موريتانيا" },
    { "question": "🇲🇺", "response": "موريشيوس" },
    { "question": "🇾🇹", "response": "مايوت" },
    { "question": "🇲🇽", "response": "المكسيك" },
    { "question": "🇫🇲", "response": "ميكرونيزيا" },
    { "question": "🇲🇩", "response": "مولدوفا" },
    { "question": "🇲🇨", "response": "موناكو" },
    { "question": "🇲🇳", "response": "منغوليا" },
    { "question": "🇲🇪", "response": "الجبل الاسود" },
    { "question": "🇲🇸", "response": "مونتسيرات" },
    { "question": "🇲🇦", "response": "المغرب" },
    { "question": "🇲🇿", "response": "موزمبيق" },
    { "question": "🇲🇲", "response": "ميانمار" },
    { "question": "🇳🇦", "response": "ناميبيا" },
    { "question": "🇳🇷", "response": "ناورو" },
    { "question": "🇳🇵", "response": "نيبال" },
    { "question": "🇳🇱", "response": "هولندا" },
    { "question": "🇳🇨", "response": "كاليدونيا الجديده" },
    { "question": "🇳🇿", "response": "نيوزيلندا" },
    { "question": "🇳🇮", "response": "نيكاراغوا" },
    { "question": "🇳🇪", "response": "النيجر" },
    { "question": "🇳🇬", "response": "نيجيريا" },
    { "question": "🇳🇺", "response": "نيوي" },
    { "question": "🇳🇫", "response": "جزيره نورفولك" },
    { "question": "🇲🇰", "response": "مقدونيا الشماليه" },
    { "question": "🇮🇪", "response": "ايرلندا الشماليه" },
    { "question": "🇲🇵", "response": "جزر مريانا الشماليه" },
    { "question": "🇳🇴", "response": "النرويج" },
    { "question": "🇴🇲", "response": "سلطانه عمان" },
    { "question": "🇵🇰", "response": "باكستان" },
    { "question": "🇵🇼", "response": "بالاو" },
    { "question": "🇵🇸", "response": "فلسطين" },
    { "question": "🇵🇦", "response": "بنما" },
    { "question": "🇵🇬", "response": "بابوا غينيا الجديده" },
    { "question": "🇵🇾", "response": "باراجواي" },
    { "question": "🇵🇪", "response": "بيرو" },
    { "question": "🇵🇭", "response": "فيلبيني" },
    { "question": "🇵🇳", "response": "جزر بيتكيرن" },
    { "question": "🇵🇱", "response": "بولندا" },
    { "question": "🇵🇹", "response": "البرتغال" },
    { "question": "🇵🇷", "response": "بورتوريكو" },
    { "question": "🇶🇦", "response": "قطر" },
    { "question": "🇷🇪", "response": "ريانيون" },
    { "question": "🇷🇴", "response": "رومانيا" },
    { "question": "🇷🇺", "response": "روسيا" },
    { "question": "🇷🇼", "response": "رواندا" },
    { "question": "🇸🇧", "response": "سانت بارتيليمي" },
    { "question": "🇸🇭", "response": "سانت هيلانه واسنشن وتريستان دا كونها" },
    { "question": "🇰🇳", "response": "سانت كيتس ونيفيس" },
    { "question": "🇱🇨", "response": "سانت لوسيا" },
    { "question": "🇲🇫", "response": "سانت مارتن" }
]
