[
  { "question": "نينجا شعره أصفر بيحب الرامن", "response": "ناروتو" },
  { "question": "نينجا عين قوية انتقامي", "response": "ساسكي" },
  { "question": "مدرب يغطي عينه ينسخ الجتسو", "response": "كاكاشي" },
  { "question": "هادئ قتل عشيرته قوي", "response": "ايتاشي" },
  { "question": "أسطورة عدو قوي يحب القتال", "response": "مادارا" },
  { "question": "قرصان مطاط ملك القراصنة", "response": "لوفي" },
  { "question": "سيوف يضيع مخلص", "response": "زورو" },
  { "question": "طباخ يحب البنات ركلات", "response": "سانجي" },
  { "question": "ملاحة فلوس ذكية", "response": "نامي" },
  { "question": "شعر أحمر قوي ذراع واحدة", "response": "شانكس" },
  { "question": "قصير قائد سريع", "response": "ليفاي" },
  { "question": "غاضب يكره العمالقة يتحول", "response": "ايرين" },
  { "question": "هادئة قوية تحمي شخص", "response": "ميكاسا" },
  { "question": "ذكي استراتيجي ضعيف جسديًا", "response": "ارمين" },
  { "question": "ذكي مذكرة يقتل بدون لمس", "response": "لايت" },
  { "question": "عبقري غريب يحب الحلويات", "response": "L" },
  { "question": "شيطان تفاح يضحك", "response": "ريوك" },
  { "question": "مقاتل قوي شعره يتغير", "response": "غوكو" },
  { "question": "أمير مغرور منافس", "response": "فيجيتا" },
  { "question": "ابن هادئ يغضب", "response": "غوهان" },
  { "question": "إله قط مدمر", "response": "بيروس" },
  { "question": "معلم عيونه مغطاة قوي جدًا", "response": "غوجو" },
  { "question": "طالب قوي يحتوي شيطان", "response": "يوجي" },
  { "question": "ملك اللعنات شرير داخل شخص", "response": "سوكونا" },
  { "question": "طالب يستدعي وحوش هادئ", "response": "ميغومي" },
  { "question": "طيب يشم يحارب الشياطين", "response": "تانجيرو" },
  { "question": "اخت شيطانة صندوق", "response": "نيزوكو" },
  { "question": "جبان ينام سريع", "response": "زينيتسو" },
  { "question": "خنزير متهور سيوف", "response": "اينوسكي" },
  { "question": "طفل محقق ذكي", "response": "كونان" },
  { "question": "نار تنين يقاتل", "response": "ناتسو" },
  { "question": "ساحرة دروع قوية", "response": "ايرزا" },
  { "question": "نصف غول شعر أبيض يعاني", "response": "كانيكي" },
  { "question": "قصير قائد قوي", "response": "ميلودياس" },
  { "question": "سحر بدون سحر عنيد", "response": "استا" },
  { "question": "ريح موهوب هادئ", "response": "يونو" },
  { "question": "قاتل كهرباء سريع", "response": "كيلوا" },
  { "question": "طفل صياد طيب", "response": "غون" },
  { "question": "مخادع يحب القتال غريب", "response": "هيسوكا" },
  { "question": "سيف شيطاني قوي غاضب", "response": "يوشيرو" },
  { "question": "ساحر عجوز قوي", "response": "يامي" },
  { "question": "فارس درع قوي", "response": "يوليوس" },
  { "question": "نينجا سريع ظل", "response": "روك لي" },
  { "question": "نينجا حلم هوكاجي أخضر", "response": "مايت غاي" },
  { "question": "محقق طفل مستكشف", "response": "دايجو" },
  { "question": "قائد منظم هادئ", "response": "غين" },
  { "question": "ساحر نار قوي", "response": "ناتسو" },
  { "question": "صياد وحوش قوس", "response": "كورابيكا" },
  { "question": "قاتل منظمة بارد", "response": "إيلومي" },
  { "question": "طفل عبقري لعبة", "response": "هيسوكا" },
  { "question": "ملك قوي غضب", "response": "ميلودياس" }
]
