[
    { "question": "🇺🇸", "response": "امريكا" },
    { "question": "🇩🇪", "response": "المانيا" },
    { "question": "🇰🇷", "response": "كوريا الجنوبية" },
    { "question": "🇰🇵", "response": "كوريا الشمالية" },
    { "question": "🇨🇳", "response": "الصين" },
    { "question": "🇯🇵", "response": "اليابان" },
    { "question": "🇷🇺", "response": "روسيا" },
    { "question": "🇫🇷", "response": "فرنسا" },
    { "question": "🇬🇧", "response": "انجلترا" },
    { "question": "🇨🇦", "response": "كندا" },
    { "question": "🇲🇽", "response": "المكسيك" },
    { "question": "🇧🇷", "response": "البرازيل" },
    { "question": "🇦🇷", "response": "الارجنتين" },
    { "question": "🇮🇳", "response": "الهند" },
    { "question": "🇹🇷", "response": "تركيا" },
    { "question": "🇮🇹", "response": "ايطاليا" },
    { "question": "🇪🇸", "response": "اسبانيا" },
    { "question": "🇳🇱", "response": "هولندا" },
    { "question": "🇸🇪", "response": "السويد" },
    { "question": "🇳🇴", "response": "النرويج" },
    { "question": "🇨🇭", "response": "سويسرا" },
    { "question": "🇦🇺", "response": "استراليا" },
    { "question": "🇪🇬", "response": "مصر" },
    { "question": "🇸🇦", "response": "السعوديه" },
    { "question": "🇦🇪", "response": "الامارات" },
    { "question": "🇶🇦", "response": "قطر" },
    { "question": "🇰🇼", "response": "الكويت" },
    { "question": "🇧🇭", "response": "البحرين" },
    { "question": "🇴🇲", "response": "عمان" },
    { "question": "🇾🇪", "response": "اليمن" },
    { "question": "🇮🇶", "response": "العراق" },
    { "question": "🇸🇾", "response": "سوريا" },
    { "question": "🇱🇧", "response": "لبنان" },
    { "question": "🇯🇴", "response": "الاردن" },
    { "question": "🇵🇸", "response": "فلسطين" },
    { "question": "🇲🇦", "response": "المغرب" },
    { "question": "🇩🇿", "response": "الجزائر" },
    { "question": "🇹🇳", "response": "تونس" },
    { "question": "🇱🇾", "response": "ليبيا" },
    { "question": "🇸🇩", "response": "السودان" },
    { "question": "🇸🇴", "response": "الصومال" },
    { "question": "🇩🇯", "response": "جيبوتي" },
    { "question": "🇰🇲", "response": "جزر القمر" },
    { "question": "🇲🇷", "response": "موريتانيا" }
]
